---
- hosts: localhost
  tasks:
    - name: Print external configuration values
      debug:
        msg: user = {{ user }}, repo = {{ repo }}
        # TODO: how to handle optional configurations? like awesome + xinitrc?
        # TODO: how to handle BIG template files like zsh/vimrc?
    - name: Show current hostname
      debug:
        msg: Running on {{ inventory_hostname }}
# Deploy all config links
    - name: "Link scripts folder"
      file:
        src: "{{ repo }}/scripts"
        dest: ~/scripts
        owner: "{{ user }}"
        state: link
# Deploy copied configs
    - name: "Deploy redshift config"
      copy:
        src: "{{ repo }}/redshift/redshift.conf"
        dest: ~/.config/redshift.conf
        mode: 0644
    - name: Print external configuration values
      debug:
        msg: AOSF {{ ansible_os_family }}

# Handle OS specific tasks
    - include_tasks: gentoo.yml
      when: ansible_os_family == "Gentoo"
    - include_tasks: debian.yml
      when: ansible_os_family == "Debian"  # TODO: needs also ubuntu
