[colors.bright]
black = "#333333"
blue = "#5c5cff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#3465A4"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#000000"
foreground = "#aaaaaa"

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "PasteSelection"
key = "P"
mods = "Control|Shift"

[shell]
program = "/bin/zsh"

[window.dimensions]
columns = 90
lines = 30
