---
- name: Linking scripts folder
  file:
    src: "{{ repo }}/scripts"
    dest: ~/scripts
    owner: "{{ user }}"
    state: link
- name: Create htop config folder
  file:
    path: ~/.config/htop
    state: directory
- name: Link htop config
  file:
    src: "{{ repo }}/htop/htoprc"
    dest: ~/.config/htop/htoprc
    owner: "{{ user }}"
    state: link
- name: Deploying alacritty config
  template:
    src: "{{ repo }}/alacritty/alacritty.toml"
    dest: ~/.alacritty.toml
- name: Linking fonts
  file:
    src: "{{ repo }}/fonts"
    dest: ~/.fonts
    owner: "{{ user }}"
    state: link
  notify:
    - update font-cache
- name: Setting up enhancd repository
  git:
    repo: "https://github.com/babarot/enhancd.git"
    dest: ~/.doto_src/enhancd
    depth: 1
    version: main
    accept_hostkey: yes
# Installation
- name: Install terminal dependencies gentoo
  portage:
    package:
      - sys-apps/bat
      - sys-apps/eza
      - dev-python/pip
      - x11-terms/alacritty
      - sys-process/htop
      - app-shells/zoxide
    state: present
  when: ansible_facts['os_family'] == "Gentoo"
  become: true
  tags:
    - install
- name: Install terminal dependencies debian
  apt:
    name:
      # - sys-apps/exa TODO: fix by manual install
      - bat
      - python3-pip
      - htop
      - build-essential
      - zoxide
    state: present
  when: ansible_facts['os_family'] == "Debian"
  become: true
  tags:
    - install
