---
- name: Linking scripts folder
  file:
    src: "{{ repo }}/scripts"
    dest: ~/scripts
    owner: "{{ user }}"
    state: link
- name: Create htop config folder
  file:
    path: ~/.config/htop
    state: directory
- name: Link htop config
  file:
    src: "{{ repo }}/htop/htoprc"
    dest: ~/.config/htop/htoprc
    owner: "{{ user }}"
    state: link
- name: Deploying alacritty config
  template:
    src: "{{ repo }}/alacritty/alacritty.yml"
    dest: ~/.alacritty.yml
- name: Linking fonts
  file:
    src: "{{ repo }}/fonts"
    dest: ~/.fonts
    owner: "{{ user }}"
    state: link
  notify:
    - update font-cache
- name: Setting up enhancd repository
  git:
    repo: "https://github.com/b4b4r07/enhancd.git"
    dest: ~/.doto_src/enhancd
    depth: 1
    accept_hostkey: yes
- name: Setting up fasd repository
  git:
    repo: "https://github.com/clvv/fasd.git"
    dest: ~/.doto_src/fasd
    depth: 1
    accept_hostkey: yes
  register: fasd_git_result
- name: Build and install fasd
  make:
    chdir: ~/.doto_src/fasd
    target: install
    params:
      PREFIX: /home/{{ user }}/
  when: fasd_git_result.after != fasd_git_result.before
# Installation
- name: Install terminal dependencies gentoo
  portage:
    package:
      - sys-apps/bat
      - sys-apps/exa
      - dev-python/pip
      - x11-terms/alacritty
      - sys-process/htop
    state: present
  when: ansible_os_family == "Gentoo"
  become: yes
  tags:
    - install
- name: Install terminal dependencies debian
  apt:
    name:
      # - sys-apps/exa TODO: fix by manual install
      - bat
      - python3-pip
      - htop
    state: present
  when: ansible_os_family == "Debian"
  become: yes
  tags:
    - install
