---
- name: Linking vim folder
  file:
    src: "{{ repo }}/vim/vim_dir"
    dest: ~/.vim
    owner: "{{ user }}"
    state: link
- name: Deploying vim config
  template:
    src: "{{ repo }}/vim/vimrc_main"
    dest: ~/.vimrc
  vars:
    llvm_version: 14
- name: Installing vim plugins
  command: vi -c 'PlugInstall | qa'
  # TODO: figure out how to not mark this changed
