---
# Installation
- name: Install vim gentoo
  portage:
    package:
      - app-editors/vim
      - app-i18n/translate-shell
    state: present
  when: ansible_os_family == "Gentoo"
  become: yes
  tags:
    - install
- name: Install vim debian
  apt:
    name:
      - vim-gtk
      - translate-shell
    state: present
  when: ansible_os_family == "Debian"
  become: yes
  tags:
    - install
# Configuration
- name: Linking vim folder
  file:
    src: "{{ repo }}/vim/vim_dir"
    dest: ~/.vim
    owner: "{{ user }}"
    state: link
- name: Linking nvim config
  file:
    src: "{{ repo }}/vim/nvim.lua"
    dest: ~/.nvim.lua
    owner: "{{ user }}"
    state: link
- name: Deploying vim config
  template:
    src: "{{ repo }}/vim/vimrc_main"
    dest: ~/.vimrc
  vars:
    llvm_version: 14
- name: Link generated vim config
  file:
    src: "~/.vimrc"
    dest: "{{ repo }}/vim/vim_dir/init.vim" # included in .gitignore, because path of source depends on system
    state: link
- name: Installing vim plugins
  command: vim +PlugInstall +qall
  args:
    stdin: "\n\n"
  changed_when: false
