---
- name: Deploying tmux config
  template:
    src: "{{ repo }}/tmux/tmux_main.conf"
    dest: ~/.tmux.conf
- name: Linking tmux folder
  file:
    src: "{{ repo }}/tmux/tmux_folder"
    dest: ~/.tmux
    owner: "{{ user }}"
    state: link
# Installation
- name: Install tmux gentoo
  portage:
    package:
      - app-misc/tmux
    state: present
  when: ansible_facts['os_family'] == "Gentoo"
  become: true
  tags:
    - install
- name: Install tmux debian
  apt:
    name:
      - tmux
    state: present
  when: ansible_facts['os_family'] == "Debian"
  become: true
  tags:
    - install
